#!/bin/sh
# DO NOT CHANGE
cd cmdhelp;make;cd build;make
cd ../..
cd tutorial;make;cd build;make
cd ../..
cd cmdhelp/build;mv cmdhelp ../../bin
cd ..
#mv tutorial/build/tutorial ../../../bin
read -p "Please enter the path to the /spectacleos folder. " BINPATH
mv $BINPATH/tutorial/build/tutorial $BINPATH/bin
#
printf "\033[1;37mDone!\033[0m\n"
echo "You can stop this process now, or if you want..."
sleep 0.5
read -p "Enter the name of your default browser (To open the graphical menu)." BROWSER
open ../menu.html -a "$BROWSER"
