#!/bin/sh
# DO NOT CHANGE
cd cmdhelp;make;cd build;make
cd ../..
cd tutorial;make;cd build;make
cd ../..
cd cmdhelp/build;mv cmdhelp ../../bin
cd ..
#mv tutorial/build/tutorial ../../../bin
read -p "$(printf "\033[1;37m")Please enter the path to the /spectacleos folder.$(printf "\033[0;36m") " BINPATH
mv $BINPATH/tutorial/build/tutorial $BINPATH/bin
#
printf "\033[1;37mDone!\033[0m\n"
echo "You can stop this process now, or if you want..."
sleep 0.5
read -p "$(printf "\033[1;37m")Enter the name of your default browser (To open the graphical menu).$(printf "\033[0;36m")" BROWSER
open ../menu.html -a "$BROWSER"
printf "\033[0m"
