import turtle
turtle.fillcolor("black")
turtle.begin_fill()
turtle.hideturtle()
turtle.write("spectacleOS", False, align="center", font=('Mukta', 20, 'normal'))
turtle.pen(fillcolor="black", pencolor="white", pensize=0)
turtle.goto(0,-20)
turtle.pen(fillcolor="black", pencolor="black", pensize=0)
turtle.write("matterhorn", False, align="center", font=('Mukta', 10, 'normal'))
turtle.pen(fillcolor="black", pencolor="white", pensize=0)
turtle.goto(0, -40)
turtle.pen(fillcolor="black", pencolor="black", pensize=0)
turtle.write("Hi there!", False, align="center", font=('Mukta', 10, 'normal'))
turtle.pen(fillcolor="black", pencolor="white", pensize=0)
turtle.goto(0, -55)
turtle.pen(fillcolor="blue", pencolor="black", pensize=0)
turtle.write("Important information can be accessed at https://l.searchme.one/specswiki.", False, align="center", font=('Mukta', 10, 'normal'))
turtle.end_fill()
turtle.done()
exit()
