import turtle
turtle.fillcolor("black")
turtle.begin_fill()
turtle.hideturtle()
turtle.write("spectacleOS", False, align="center", font=('Mukta', 20, 'normal'))
turtle.pen(fillcolor="black", pencolor="white", pensize=0)
turtle.goto(0,-20)
turtle.pen(fillcolor="black", pencolor="black", pensize=0)
turtle.write("matterhorn", False, align="center", font=('Mukta', 10, 'normal'))
turtle.pen(fillcolor="black", pencolor="white", pensize=0)
turtle.goto(0, -40)
turtle.pen(fillcolor="black", pencolor="black", pensize=0)
turtle.write("Hi there!", False, align="center", font=('Mukta', 10, 'normal'))
turtle.pen(fillcolor="black", pencolor="white", pensize=0)
turtle.goto(0, -55)
turtle.pen(fillcolor="blue", pencolor="blue", pensize=0)
turtle.write("Important information can be accessed at https://l.searchme.one/specswiki.", False, align="center", font=('Mukta', 10, 'normal'))
turtle.pen(fillcolor="", pencolor="", pensize=0)
turtle.setpos(-180, 100)
turtle.seth(0)
turtle.pen(fillcolor="", pencolor="black", pensize=0)
turtle.forward(350)
turtle.right(90)
turtle.forward(200)
turtle.right(90)
turtle.forward(350)
turtle.right(90)
turtle.forward(200)
turtle.pen(fillcolor="", pencolor="", pensize=0)
turtle.setpos(170,100)
turtle.pen(fillcolor="", pencolor="black", pensize=0)
turtle.seth(270)
turtle.forward(200)
turtle.left(45)
turtle.forward(100)
turtle.right(135)
turtle.forward(492)
turtle.right(135)
turtle.forward(100)
turtle.end_fill()
turtle.done()
