#!/bin/sh
printf "\033[1;34m"
if [ $1 -z ]
then
	./bin/cmdhelpS0.rb
elif [ $1 = "-h" ]
then
	./bin/cmdhelp

elif [ $1 = "start" ]
then
	python3 -m pip install maskpass
	clear;python3 fuzz.py


elif [ $1 = "-sboot" ]
then
	clear;./bin/sboot

elif [ $1 = "--updates" ]
then
	clear;./bin/checkupdates


elif [ $1 = "--tutorial" ]
then
	clear;./bin/tutorial
fi
printf "\033[0m"
